const FETCH_STREAMS = "FETCH_STREAMS";
const FETCH_STREAM = "FETCH_STREAM";
const UPDATE_STREAM = "UPDATE_STREAM";
const DELETE_STREAM = "DELETE_STREAM";

export { FETCH_STREAMS, FETCH_STREAM, UPDATE_STREAM, DELETE_STREAM };
